// Automatically generated by build-categories.ts - DO NOT EDIT MANUALLY
import { CategoryInfo } from './types';

export const STATIC_CATEGORIES: (CategoryInfo & { count: number; subCategories?: string[] })[] = [
  {
    "id": "Text Tools",
    "slug": "text-tools",
    "name": "Text Tools",
    "iconName": "FileText",
    "description": "Transform, clean, format, and analyze text instantly without data leaving your browser.",
    "colorGradient": "from-indigo-500 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 4209,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Image Tools",
    "slug": "image-tools",
    "name": "Image Tools",
    "iconName": "Image",
    "description": "Crop, resize, compress, and convert images directly in your browser with canvas API.",
    "colorGradient": "from-pink-500 to-rose-600",
    "bgLight": "bg-pink-50 text-pink-700",
    "count": 4208,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "PDF Tools",
    "slug": "pdf-tools",
    "name": "PDF Tools",
    "iconName": "FileCheck",
    "description": "Inspect PDF metadata, count pages, generate clean PDF previews, and extract text client-side.",
    "colorGradient": "from-orange-500 to-amber-600",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 2708,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Developer Tools",
    "slug": "developer-tools",
    "name": "Developer Tools",
    "iconName": "Code",
    "description": "JSON formatters, Base64, UUID generators, HTML entity encoders, and code helpers.",
    "colorGradient": "from-emerald-500 to-teal-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 4209,
    "subCategories": [
      "Browser",
      "Client-side",
      "Custom",
      "Dynamic",
      "Private"
    ]
  },
  {
    "id": "SEO Tools",
    "slug": "seo-tools",
    "name": "SEO Tools",
    "iconName": "Search",
    "description": "Generate Meta tags, analyze keyword density, audit title lengths, and craft schema tags.",
    "colorGradient": "from-purple-500 to-violet-600",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 1808,
    "subCategories": [
      "Custom",
      "Browser",
      "Client-side",
      "Dynamic",
      "Private"
    ]
  },
  {
    "id": "Color Tools",
    "slug": "color-tools",
    "name": "Color Tools",
    "iconName": "Palette",
    "description": "Hex, RGB, HSL converters, contrast checkers, and CSS gradient generators.",
    "colorGradient": "from-cyan-500 to-sky-600",
    "bgLight": "bg-violet-50 text-violet-700",
    "count": 1192,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Converter Tools",
    "slug": "converter-tools",
    "name": "Converter Tools",
    "iconName": "RefreshCw",
    "description": "Convert length, weight, speed, temperature, and digital storage units accurately.",
    "colorGradient": "from-yellow-500 to-orange-600",
    "bgLight": "bg-sky-50 text-sky-700",
    "count": 4168,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Calculator Tools",
    "slug": "calculator-tools",
    "name": "Calculator Tools",
    "iconName": "Calculator",
    "description": "Discount, sales tax, percentage, margin, and loan payment calculators.",
    "colorGradient": "from-green-500 to-lime-600",
    "bgLight": "bg-lime-50 text-lime-700",
    "count": 4188,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Security Tools",
    "slug": "security-tools",
    "name": "Security Tools",
    "iconName": "ShieldCheck",
    "description": "High-entropy password generator, SHA-256 hash generator, and key strength tester.",
    "colorGradient": "from-red-500 to-pink-600",
    "bgLight": "bg-red-50 text-red-700",
    "count": 1660,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Web Tools",
    "slug": "web-tools",
    "name": "Web Tools",
    "iconName": "Globe",
    "description": "QR Code generators, URL encoder/decoders, and web inspector utilities.",
    "colorGradient": "from-blue-500 to-indigo-600",
    "bgLight": "bg-purple-50 text-purple-700",
    "count": 1613,
    "subCategories": [
      "Dynamic",
      "Browser",
      "Client-side",
      "Custom",
      "Private"
    ]
  },
  {
    "id": "Social Media Tools",
    "slug": "social-media-tools",
    "name": "Social Media Tools",
    "iconName": "Share2",
    "description": "Bio generators, caption formatters, hashtag generators, and image sizing helpers.",
    "colorGradient": "from-fuchsia-500 to-rose-600",
    "bgLight": "bg-fuchsia-50 text-fuchsia-700",
    "count": 1650,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Video Tools",
    "slug": "video-tools",
    "name": "Video Tools",
    "iconName": "Video",
    "description": "Video metadata inspectors, frame extractors, canvas video croppers and format tools.",
    "colorGradient": "from-purple-600 to-pink-600",
    "bgLight": "bg-purple-50 text-purple-700",
    "count": 1100,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Audio Tools",
    "slug": "audio-tools",
    "name": "Audio Tools",
    "iconName": "Music",
    "description": "Audio waveform previewers, frequency analyzers, and Web Audio API tools.",
    "colorGradient": "from-cyan-500 to-blue-600",
    "bgLight": "bg-cyan-50 text-cyan-700",
    "count": 1100,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "File Tools",
    "slug": "file-tools",
    "name": "File Tools",
    "iconName": "FolderArchive",
    "description": "Archive inspectors, file checksum calculators, file diff checkers, and metadata tools.",
    "colorGradient": "from-amber-600 to-yellow-500",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 1650,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Generators",
    "slug": "generators",
    "name": "Generators",
    "iconName": "Sparkles",
    "description": "Random data generators, UUIDs, QR codes, passwords, and mock data suites.",
    "colorGradient": "from-indigo-600 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 1930,
    "subCategories": [
      "Dynamic",
      "Browser",
      "Custom",
      "Client-side",
      "Private"
    ]
  },
  {
    "id": "Math Tools",
    "slug": "math-tools",
    "name": "Math Tools",
    "iconName": "Calculator",
    "description": "Algebra solvers, matrix calculators, statistical analyzers, and geometry tools.",
    "colorGradient": "from-emerald-600 to-teal-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 1985,
    "subCategories": [
      "Client-side",
      "Custom",
      "Private",
      "Browser",
      "Dynamic"
    ]
  },
  {
    "id": "Date & Time",
    "slug": "date-time",
    "name": "Date & Time",
    "iconName": "Clock",
    "description": "Timezone converters, date duration calculators, age calculators, and timestamps.",
    "colorGradient": "from-blue-600 to-indigo-600",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 1015,
    "subCategories": [
      "Dynamic",
      "Private",
      "Client-side",
      "Browser",
      "Custom"
    ]
  },
  {
    "id": "Productivity",
    "slug": "productivity",
    "name": "Productivity",
    "iconName": "CheckSquare",
    "description": "Timer scratchpads, task checklists, habit trackers, and document layout tools.",
    "colorGradient": "from-teal-500 to-emerald-600",
    "bgLight": "bg-teal-50 text-teal-700",
    "count": 2000,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Finance Tools",
    "slug": "finance-tools",
    "name": "Finance Tools",
    "iconName": "DollarSign",
    "description": "Mortgage, interest, ROI, NPV, amortization, and financial growth planners.",
    "colorGradient": "from-green-600 to-emerald-700",
    "bgLight": "bg-green-50 text-green-700",
    "count": 2410,
    "subCategories": [
      "Client-side",
      "Browser",
      "Custom",
      "Dynamic",
      "Private"
    ]
  },
  {
    "id": "Business Tools",
    "slug": "business-tools",
    "name": "Business Tools",
    "iconName": "Briefcase",
    "description": "Invoice formatters, margin calculators, business planning, and ROI tools.",
    "colorGradient": "from-slate-700 to-slate-900",
    "bgLight": "bg-slate-100 text-slate-800",
    "count": 1650,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Health & Fitness",
    "slug": "health-fitness",
    "name": "Health & Fitness",
    "iconName": "Activity",
    "description": "BMI, TDEE, macronutrient ratios, body fat %, and pace calculators.",
    "colorGradient": "from-rose-500 to-red-600",
    "bgLight": "bg-rose-50 text-rose-700",
    "count": 1050,
    "subCategories": [
      "Browser",
      "Client-side",
      "Custom",
      "Private",
      "Dynamic"
    ]
  },
  {
    "id": "Education",
    "slug": "education",
    "name": "Education",
    "iconName": "GraduationCap",
    "description": "GPA calculators, test score converters, reading speed analyzers, and study tools.",
    "colorGradient": "from-violet-600 to-indigo-700",
    "bgLight": "bg-violet-50 text-violet-700",
    "count": 1635,
    "subCategories": [
      "Custom",
      "Dynamic",
      "Private",
      "Browser",
      "Client-side"
    ]
  },
  {
    "id": "Unit Converters",
    "slug": "unit-converters",
    "name": "Unit Converters",
    "iconName": "RefreshCw",
    "description": "Multi-unit conversion engines for physics, geometry, data, and daily metrics.",
    "colorGradient": "from-sky-500 to-blue-600",
    "bgLight": "bg-sky-50 text-sky-700",
    "count": 1450,
    "subCategories": [
      "Client-side",
      "Private",
      "Browser",
      "Dynamic",
      "Custom"
    ]
  },
  {
    "id": "Automotive",
    "slug": "automotive",
    "name": "Automotive",
    "iconName": "Car",
    "description": "Fuel cost, car loan, depreciation, maintenance, and EV range calculators.",
    "colorGradient": "from-red-600 to-orange-600",
    "bgLight": "bg-red-50 text-red-700",
    "count": 900,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Travel Tools",
    "slug": "travel-tools",
    "name": "Travel Tools",
    "iconName": "Compass",
    "description": "Trip planners, packing lists, currency tools, and flight cost estimators.",
    "colorGradient": "from-amber-500 to-orange-600",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 1200,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Real Estate",
    "slug": "real-estate",
    "name": "Real Estate",
    "iconName": "Home",
    "description": "Mortgage, rental yield, property tax, and home inspection estimators.",
    "colorGradient": "from-emerald-600 to-teal-700",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 850,
    "subCategories": [
      "Mortgage loan payment calculator",
      "Property down payment planner",
      "Closing cost estimator",
      "Home appraisal estimator",
      "Home value appreciation"
    ]
  },
  {
    "id": "Legal Tools",
    "slug": "legal-tools",
    "name": "Legal Tools",
    "iconName": "FileText",
    "description": "Contract templates, NDA generators, privacy policies, and legal agreements.",
    "colorGradient": "from-slate-700 to-slate-900",
    "bgLight": "bg-slate-100 text-slate-800",
    "count": 865,
    "subCategories": [
      "Contract builder template",
      "Non disclosure agreement nda builder",
      "Lease agreement template",
      "Promissory note generator",
      "Power of attorney template"
    ]
  },
  {
    "id": "HR & Payroll",
    "slug": "hr-payroll",
    "name": "HR & Payroll",
    "iconName": "Users",
    "description": "Salary calculators, payslip generators, attendance logs, and tax deductions.",
    "colorGradient": "from-indigo-600 to-purple-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 1200,
    "subCategories": [
      "Client-side",
      "Custom",
      "Dynamic",
      "Private",
      "Browser"
    ]
  },
  {
    "id": "Accounting",
    "slug": "accounting",
    "name": "Accounting",
    "iconName": "CreditCard",
    "description": "General ledger tools, P&L statements, balance sheet builders, and trial balances.",
    "colorGradient": "from-blue-600 to-cyan-600",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 1165,
    "subCategories": [
      "Dynamic",
      "Client-side",
      "Custom",
      "Browser",
      "General ledger entry helper"
    ]
  },
  {
    "id": "E-commerce",
    "slug": "e-commerce",
    "name": "E-commerce",
    "iconName": "ShoppingBag",
    "description": "SKU generators, product margin tools, shipping estimators, and cart calculators.",
    "colorGradient": "from-fuchsia-600 to-pink-600",
    "bgLight": "bg-fuchsia-50 text-fuchsia-700",
    "count": 1200,
    "subCategories": [
      "Product sku generator",
      "Product barcode generator",
      "Product margin calculator",
      "Product bundle pricing",
      "Shipping fee estimator"
    ]
  },
  {
    "id": "Inventory & Logistics",
    "slug": "inventory-logistics",
    "name": "Inventory & Logistics",
    "iconName": "Box",
    "description": "Stock level auditors, warehouse bin tools, freight cost, and tracking helpers.",
    "colorGradient": "from-amber-600 to-yellow-600",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 1200,
    "subCategories": [
      "Stock reorder point calculator",
      "Inventory valuation fifo lifo",
      "Warehouse bin locator helper",
      "Sku barcode generator",
      "Freight shipping cost estimator"
    ]
  },
  {
    "id": "Engineering",
    "slug": "engineering",
    "name": "Engineering",
    "iconName": "Cpu",
    "description": "Beam stress, structural load, fluid dynamics, and circuit calculators.",
    "colorGradient": "from-cyan-600 to-blue-700",
    "bgLight": "bg-cyan-50 text-cyan-700",
    "count": 1500,
    "subCategories": [
      "Beam bending stress calculator",
      "Column structural load calculator",
      "Staircase rise run calculator",
      "Truss member force solver",
      "Fluid pipe pressure drop calculator"
    ]
  },
  {
    "id": "Construction",
    "slug": "construction",
    "name": "Construction",
    "iconName": "HardHat",
    "description": "Concrete mix ratios, rebar estimators, tile counts, and wall plaster tools.",
    "colorGradient": "from-orange-600 to-amber-600",
    "bgLight": "bg-orange-50 text-orange-700",
    "count": 900,
    "subCategories": [
      "Concrete mix volume calculator",
      "Rebar steel weight calculator",
      "Wall brick count estimator",
      "Floor tile count estimator",
      "Wall paint area calculator"
    ]
  },
  {
    "id": "Electrical & Solar",
    "slug": "electrical-solar",
    "name": "Electrical & Solar",
    "iconName": "Zap",
    "description": "Ohm",
    "colorGradient": "from-yellow-500 to-amber-600",
    "bgLight": "bg-yellow-50 text-yellow-800",
    "count": 900,
    "subCategories": [
      "Ohms law voltage current calculator",
      "Wire gauge voltage drop calculator",
      "Circuit breaker ampere sizing",
      "Solar panel array roi calculator",
      "Solar battery storage sizing"
    ]
  },
  {
    "id": "Agriculture",
    "slug": "agriculture",
    "name": "Agriculture",
    "iconName": "Sprout",
    "description": "Crop yield estimators, seed requirements, NPK fertilizer, and soil tools.",
    "colorGradient": "from-emerald-500 to-green-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 900,
    "subCategories": [
      "Crop yield per acre calculator",
      "Seed requirement calculator",
      "Npk fertilizer mixture calculator",
      "Drip irrigation flow calculator",
      "Soil ph amendment estimator"
    ]
  },
  {
    "id": "Restaurant & Cafe",
    "slug": "restaurant-cafe",
    "name": "Restaurant & Cafe",
    "iconName": "Utensils",
    "description": "Recipe costing, food portioning, menu margin, and billing tip calculators.",
    "colorGradient": "from-rose-500 to-red-600",
    "bgLight": "bg-rose-50 text-rose-700",
    "count": 900,
    "subCategories": [
      "Recipe food costing calculator",
      "Menu item margin calculator",
      "Food portion size estimator",
      "Restaurant pos billing tip calculator",
      "Combo meal pricing helper"
    ]
  },
  {
    "id": "Beauty & Salon",
    "slug": "beauty-salon",
    "name": "Beauty & Salon",
    "iconName": "Scissors",
    "description": "Salon booking helpers, haircut timers, skin care logs, and appointment tools.",
    "colorGradient": "from-pink-500 to-rose-600",
    "bgLight": "bg-pink-50 text-pink-700",
    "count": 500,
    "subCategories": [
      "Salon appointment scheduler",
      "Hair dye mix ratio helper",
      "Skin care routine planner",
      "Nail art service price estimator",
      "Client-side"
    ]
  },
  {
    "id": "Wedding & Event",
    "slug": "wedding-event",
    "name": "Wedding & Event",
    "iconName": "Heart",
    "description": "Seating charts, guest list managers, wedding budget planners, and RSVP tools.",
    "colorGradient": "from-purple-500 to-pink-600",
    "bgLight": "bg-purple-50 text-purple-700",
    "count": 500,
    "subCategories": [
      "Wedding budget calculator",
      "Guest list rsvp tracker",
      "Seating chart planner",
      "Catering food quantity estimator",
      "Event timeline schedule builder"
    ]
  },
  {
    "id": "Photography",
    "slug": "photography",
    "name": "Photography",
    "iconName": "Camera",
    "description": "EXIF inspectors, depth of field calculators, aspect ratio croppers, and exposure tools.",
    "colorGradient": "from-slate-600 to-slate-800",
    "bgLight": "bg-slate-100 text-slate-800",
    "count": 900,
    "subCategories": [
      "Exif metadata inspector",
      "Depth of field dof calculator",
      "Aspect ratio cropper guide",
      "Camera exposure triangle solver",
      "Field of view fov calculator"
    ]
  },
  {
    "id": "Music Production",
    "slug": "music-production",
    "name": "Music Production",
    "iconName": "Music",
    "description": "BPM metronomes, chord progression builders, scale charts, and audio tuners.",
    "colorGradient": "from-indigo-600 to-violet-700",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 900,
    "subCategories": [
      "Bpm metronome tool",
      "Music key transposer",
      "Chord progression generator",
      "Bpm to millisecond delay calculator",
      "Guitar tuner pitch reference"
    ]
  },
  {
    "id": "Environment & Energy",
    "slug": "environment-energy",
    "name": "Environment & Energy",
    "iconName": "Leaf",
    "description": "Carbon footprint calculators, emission auditors, and energy efficiency estimators.",
    "colorGradient": "from-teal-600 to-emerald-700",
    "bgLight": "bg-teal-50 text-teal-700",
    "count": 900,
    "subCategories": [
      "Carbon footprint emission calculator",
      "Co2 savings estimator",
      "Solar energy offset calculator",
      "Recycling impact estimator",
      "Client-side"
    ]
  },
  {
    "id": "Pets & Animals",
    "slug": "pets-animals",
    "name": "Pets & Animals",
    "iconName": "Dog",
    "description": "Pet calorie requirements, age in human years, grooming, and feeding guides.",
    "colorGradient": "from-amber-500 to-orange-500",
    "bgLight": "bg-amber-50 text-amber-800",
    "count": 500,
    "subCategories": [
      "Pet calorie requirement calculator",
      "Dog age in human years calculator",
      "Cat age converter",
      "Pet medication dosage helper",
      "Client-side"
    ]
  },
  {
    "id": "Government & Public Services",
    "slug": "government-public-services",
    "name": "Government & Public Services",
    "iconName": "Building",
    "description": "Utility bill calculators, document checklist helpers, and civic tax estimators.",
    "colorGradient": "from-blue-700 to-slate-800",
    "bgLight": "bg-blue-50 text-blue-800",
    "count": 500,
    "subCategories": [
      "Property tax valuation calculator",
      "Vehicle road tax estimator",
      "Public utility bill splitter",
      "Civic tax estimator",
      "Client-side"
    ]
  },
  {
    "id": "Office Administration",
    "slug": "office-administration",
    "name": "Office Administration",
    "iconName": "File",
    "description": "Letterhead builders, memo formatters, visitor logs, and office form tools.",
    "colorGradient": "from-slate-600 to-slate-900",
    "bgLight": "bg-slate-100 text-slate-800",
    "count": 900,
    "subCategories": [
      "Office memo formatter",
      "Business letterhead builder",
      "Visitor log table",
      "Meeting agenda builder",
      "Office expense voucher builder"
    ]
  },
  {
    "id": "Networking",
    "slug": "networking",
    "name": "Networking",
    "iconName": "Network",
    "description": "Subnet mask calculators, CIDR notation solvers, port lookup, and ping tools.",
    "colorGradient": "from-indigo-600 to-blue-700",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 900,
    "subCategories": [
      "Ip subnet mask calculator",
      "Cidr notation range solver",
      "Network port lookup",
      "Bandwidth download time calculator",
      "Ping latency estimator"
    ]
  },
  {
    "id": "Data Management",
    "slug": "data-management",
    "name": "Data Management",
    "iconName": "Database",
    "description": "SQL schema generators, data deduplicators, JSON formatters, and CSV tools.",
    "colorGradient": "from-blue-600 to-indigo-700",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 900,
    "subCategories": [
      "Sql table schema builder",
      "Data deduplication helper",
      "Json field extractor",
      "Csv column reorder tool",
      "Data normalization checker"
    ]
  },
  {
    "id": "Project Management",
    "slug": "project-management",
    "name": "Project Management",
    "iconName": "Briefcase",
    "description": "Gantt chart planners, story point estimators, RACI matrix tools, and WBS boards.",
    "colorGradient": "from-teal-600 to-emerald-700",
    "bgLight": "bg-teal-50 text-teal-700",
    "count": 900,
    "subCategories": [
      "Gantt chart timeline builder",
      "Story point estimation calculator",
      "Raci matrix planner",
      "Wbs work breakdown structure builder",
      "Sprint velocity calculator"
    ]
  },
  {
    "id": "Marketing & Advertising",
    "slug": "marketing-advertising",
    "name": "Marketing & Advertising",
    "iconName": "Megaphone",
    "description": "Ad copy builders, ROAS calculators, CTR estimator, and landing page tools.",
    "colorGradient": "from-rose-600 to-fuchsia-600",
    "bgLight": "bg-rose-50 text-rose-700",
    "count": 1200,
    "subCategories": [
      "Ad campaign roas calculator",
      "Click through rate ctr calculator",
      "Cost per click cpc estimator",
      "Cost per acquisition cpa calculator",
      "Ad banner aspect ratio helper"
    ]
  },
  {
    "id": "YouTube Creator Tools",
    "slug": "youtube-creator-tools",
    "name": "YouTube Creator Tools",
    "iconName": "Video",
    "description": "YouTube title generators, tag extractors, thumbnail checkers, and short planners.",
    "colorGradient": "from-red-600 to-rose-700",
    "bgLight": "bg-red-50 text-red-700",
    "count": 1200,
    "subCategories": [
      "Youtube title character counter",
      "Youtube tag extractor helper",
      "Youtube channel keyword finder",
      "Youtube thumbnail previewer",
      "Youtube shorts aspect ratio tool"
    ]
  },
  {
    "id": "Freelancing",
    "slug": "freelancing",
    "name": "Freelancing",
    "iconName": "Briefcase",
    "description": "Freelance rate calculators, proposal templates, contract generators, and invoice tools.",
    "colorGradient": "from-indigo-600 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 900,
    "subCategories": [
      "Freelance hourly rate calculator",
      "Project quote estimate builder",
      "Freelance contract template builder",
      "Freelance invoice builder",
      "Client project milestone tracker"
    ]
  }
];

import { SEARCH_INDEX } from './search-index';

const UNIQUE_GRADIENTS = [
  'from-indigo-500 to-blue-600',
  'from-pink-500 to-rose-600',
  'from-orange-500 to-amber-600',
  'from-emerald-500 to-teal-600',
  'from-purple-500 to-violet-600',
  'from-cyan-500 to-sky-600',
  'from-yellow-500 to-orange-600',
  'from-green-500 to-lime-600',
  'from-red-500 to-pink-600',
  'from-blue-500 to-indigo-600',
  'from-fuchsia-500 to-pink-600',
  'from-violet-500 to-purple-600',
  'from-rose-500 to-orange-500',
  'from-teal-500 to-cyan-600',
  'from-lime-500 to-emerald-600',
  'from-amber-500 to-yellow-600',
  'from-sky-500 to-indigo-600',
  'from-purple-600 to-pink-600',
  'from-emerald-600 to-green-600',
  'from-indigo-600 to-violet-700',
  'from-rose-600 to-fuchsia-600',
  'from-cyan-600 to-blue-700',
  'from-emerald-500 to-green-600',
  'from-pink-600 to-purple-600',
  'from-yellow-600 to-amber-600'
];

const SUBCATEGORY_RULES: { parent: string; keyword: string; name: string }[] = [
  // Text Tools
  { parent: 'Text Tools', keyword: 'counter', name: 'Word Counters' },
  { parent: 'Text Tools', keyword: 'count', name: 'Word Counters' },
  { parent: 'Text Tools', keyword: 'case', name: 'Case Converters' },
  { parent: 'Text Tools', keyword: 'convert', name: 'Text Converters' },
  { parent: 'Text Tools', keyword: 'format', name: 'Text Formatters' },
  { parent: 'Text Tools', keyword: 'lorem', name: 'Text Generators' },
  { parent: 'Text Tools', keyword: 'dummy', name: 'Text Generators' },
  { parent: 'Text Tools', keyword: 'generator', name: 'Text Generators' },
  { parent: 'Text Tools', keyword: 'analyze', name: 'Content Analyzers' },
  { parent: 'Text Tools', keyword: 'analyzer', name: 'Content Analyzers' },
  { parent: 'Text Tools', keyword: 'analysis', name: 'Content Analyzers' },
  { parent: 'Text Tools', keyword: 'validate', name: 'Text Validators' },
  { parent: 'Text Tools', keyword: 'validator', name: 'Text Validators' },
  { parent: 'Text Tools', keyword: 'clean', name: 'Text Cleaners' },
  { parent: 'Text Tools', keyword: 'diff', name: 'Text Comparators' },

  // Image Tools
  { parent: 'Image Tools', keyword: 'resize', name: 'Image Resizers' },
  { parent: 'Image Tools', keyword: 'crop', name: 'Image Croppers' },
  { parent: 'Image Tools', keyword: 'convert', name: 'Image Converters' },
  { parent: 'Image Tools', keyword: 'filter', name: 'Image Filters' },
  { parent: 'Image Tools', keyword: 'compress', name: 'Image Compressors' },
  { parent: 'Image Tools', keyword: 'palette', name: 'Color Palette Extractors' },

  // PDF Tools
  { parent: 'PDF Tools', keyword: 'merge', name: 'PDF Mergers' },
  { parent: 'PDF Tools', keyword: 'split', name: 'PDF Splitters' },
  { parent: 'PDF Tools', keyword: 'extract', name: 'PDF Content Extractors' },
  { parent: 'PDF Tools', keyword: 'inspect', name: 'PDF Metadata Inspectors' },

  // Developer Tools
  { parent: 'Developer Tools', keyword: 'json', name: 'JSON Formatters' },
  { parent: 'Developer Tools', keyword: 'base64', name: 'Base64 Encoders/Decoders' },
  { parent: 'Developer Tools', keyword: 'uuid', name: 'UUID/GUID Generators' },
  { parent: 'Developer Tools', keyword: 'guid', name: 'UUID/GUID Generators' },
  { parent: 'Developer Tools', keyword: 'html', name: 'HTML Encoders/Decoders' },
  { parent: 'Developer Tools', keyword: 'xml', name: 'XML Formatters' },
  { parent: 'Developer Tools', keyword: 'yaml', name: 'YAML Converters' },

  // SEO Tools
  { parent: 'SEO Tools', keyword: 'meta', name: 'Meta Tag Generators' },
  { parent: 'SEO Tools', keyword: 'keyword', name: 'Keyword Analyzers' },
  { parent: 'SEO Tools', keyword: 'schema', name: 'Schema Tag Creators' },
  { parent: 'SEO Tools', keyword: 'sitemap', name: 'Sitemap Generators' },

  // Color Tools
  { parent: 'Color Tools', keyword: 'contrast', name: 'Contrast Checkers' },
  { parent: 'Color Tools', keyword: 'picker', name: 'Color Pickers' },
  { parent: 'Color Tools', keyword: 'gradient', name: 'Gradient Generators' },
  { parent: 'Color Tools', keyword: 'convert', name: 'Color Code Converters' },

  // Converter Tools
  { parent: 'Converter Tools', keyword: 'length', name: 'Length Converters' },
  { parent: 'Converter Tools', keyword: 'weight', name: 'Weight Converters' },
  { parent: 'Converter Tools', keyword: 'speed', name: 'Speed Converters' },
  { parent: 'Converter Tools', keyword: 'temperature', name: 'Temperature Converters' },
  { parent: 'Converter Tools', keyword: 'storage', name: 'Digital Storage Converters' },

  // Calculator Tools
  { parent: 'Calculator Tools', keyword: 'discount', name: 'Discount Calculators' },
  { parent: 'Calculator Tools', keyword: 'tax', name: 'Sales Tax Calculators' },
  { parent: 'Calculator Tools', keyword: 'percentage', name: 'Percentage Calculators' },
  { parent: 'Calculator Tools', keyword: 'loan', name: 'Loan Calculators' },

  // Security Tools
  { parent: 'Security Tools', keyword: 'password', name: 'Password Generators' },
  { parent: 'Security Tools', keyword: 'hash', name: 'Hash Generators' },
  { parent: 'Security Tools', keyword: 'strength', name: 'Key Strength Testers' },

  // Web Tools
  { parent: 'Web Tools', keyword: 'qr', name: 'QR Code Generators' },
  { parent: 'Web Tools', keyword: 'url', name: 'URL Encoders/Decoders' },
  { parent: 'Web Tools', keyword: 'inspector', name: 'Web Inspectors' },

  // Social Media Tools
  { parent: 'Social Media Tools', keyword: 'caption', name: 'Caption Formatters' },
  { parent: 'Social Media Tools', keyword: 'hashtag', name: 'Hashtag Generators' },
  { parent: 'Social Media Tools', keyword: 'bio', name: 'Bio Generators' },

  // Video Tools
  { parent: 'Video Tools', keyword: 'crop', name: 'Video Croppers' },
  { parent: 'Video Tools', keyword: 'frame', name: 'Frame Extractors' },
  { parent: 'Video Tools', keyword: 'metadata', name: 'Video Inspectors' },

  // Audio Tools
  { parent: 'Audio Tools', keyword: 'frequency', name: 'Frequency Analyzers' },
  { parent: 'Audio Tools', keyword: 'waveform', name: 'Waveform Analyzers' },

  // File Tools
  { parent: 'File Tools', keyword: 'checksum', name: 'Checksum Calculators' },
  { parent: 'File Tools', keyword: 'diff', name: 'File Diff Checkers' },

  // Generators
  { parent: 'Generators', keyword: 'mock', name: 'Mock Data Suites' },
  { parent: 'Generators', keyword: 'qr', name: 'QR Code Generators' },

  // Math Tools
  { parent: 'Math Tools', keyword: 'matrix', name: 'Matrix Calculators' },
  { parent: 'Math Tools', keyword: 'algebra', name: 'Algebra Solvers' },

  // Date & Time
  { parent: 'Date & Time', keyword: 'timezone', name: 'Timezone Converters' },
  { parent: 'Date & Time', keyword: 'duration', name: 'Date Duration Calculators' },

  // Finance Tools
  { parent: 'Finance Tools', keyword: 'mortgage', name: 'Mortgage Planners' },
  { parent: 'Finance Tools', keyword: 'roi', name: 'ROI Calculators' },

  // Business Tools
  { parent: 'Business Tools', keyword: 'invoice', name: 'Invoice Formatters' },

  // Health & Fitness
  { parent: 'Health & Fitness', keyword: 'bmi', name: 'BMI Calculators' },

  // Unit Converters
  { parent: 'Unit Converters', keyword: 'unit', name: 'Unit Converters' },

  // Construction
  { parent: 'Construction', keyword: 'concrete', name: 'Concrete Mix Calculators' },
  { parent: 'Construction', keyword: 'rebar', name: 'Rebar Estimators' },

  // Electrical & Solar
  { parent: 'Electrical & Solar', keyword: 'ohm', name: 'Ohm Law Calculators' },
  { parent: 'Electrical & Solar', keyword: 'solar', name: 'Solar Array Estimators' },

  // Agriculture
  { parent: 'Agriculture', keyword: 'yield', name: 'Crop Yield Estimators' },
  { parent: 'Agriculture', keyword: 'seed', name: 'Seed Calculators' },

  // Photography
  { parent: 'Photography', keyword: 'exif', name: 'EXIF Inspectors' },

  // Music Production
  { parent: 'Music Production', keyword: 'metronome', name: 'BPM Metronomes' },
  { parent: 'Music Production', keyword: 'chord', name: 'Chord Progression Builders' },

  // Environment & Energy
  { parent: 'Environment & Energy', keyword: 'carbon', name: 'Carbon Footprint Calculators' },

  // Data Management
  { parent: 'Data Management', keyword: 'sql', name: 'SQL Schema Tools' },
];

export const CATEGORIES: (CategoryInfo & {
  count: number;
  subCategories?: string[];
  parentId?: string;
  parentSlug?: string;
  toolSlugs: string[];
})[] = (() => {
  const finalCategories: (CategoryInfo & {
    count: number;
    subCategories?: string[];
    parentId?: string;
    parentSlug?: string;
    toolSlugs: string[];
  })[] = [];

  let gradientIndex = 0;

  const kebabCase = (str: string) => {
    return str
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .trim()
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-');
  };

  STATIC_CATEGORIES.forEach(baseCat => {
    const categoryTools = SEARCH_INDEX.filter(t => t.category === baseCat.id);
    if (categoryTools.length === 0) return;

    const grouped: Record<string, typeof categoryTools> = {};

    categoryTools.forEach(tool => {
      const nameLower = tool.name.toLowerCase();
      const tags = tool.tags || [];

      const matches = (kw: string) => {
        return nameLower.includes(kw) || tags.some((t: string) => t.toLowerCase().includes(kw));
      };

      let assignedGroup = '';

      for (const rule of SUBCATEGORY_RULES) {
        if (rule.parent === baseCat.id && matches(rule.keyword)) {
          assignedGroup = rule.name;
          break;
        }
      }

      if (!assignedGroup) {
        const bannedTags = new Set([
          'tags', 'online', 'master', 'advanced', 'smart', 'browser tool', 'client side', 'universal', 
          'helper', 'utility', 'tool', 'free', 'instant', 'easy', 'quick', 'fast', 'best', 'pro', 
          'simple', 'convert', 'converter', 'app', 'online tool', 'generator', 'generator tool', 'tools', 'client-side',
          baseCat.slug, baseCat.slug.replace('-tools', ''), baseCat.name.toLowerCase(), ...baseCat.name.toLowerCase().split(/\s+/)
        ]);

        for (const tag of tags) {
          const cleanTag = tag.toLowerCase().trim();
          if (cleanTag && !bannedTags.has(cleanTag) && cleanTag.length > 2) {
            const words = cleanTag.split(/[\s_-]+/);
            const capWords = words.map(w => w.charAt(0).toUpperCase() + w.slice(1));
            let capName = capWords.join(' ');
            
            const lowerCap = capName.toLowerCase();
            if (!lowerCap.endsWith('s') && !lowerCap.endsWith('tools') && !lowerCap.endsWith('utilities')) {
              if (lowerCap.endsWith('calculator')) {
                capName = capName + 's';
              } else if (lowerCap.endsWith('converter')) {
                capName = capName + 's';
              } else if (lowerCap.endsWith('generator')) {
                capName = capName + 's';
              } else if (lowerCap.endsWith('format')) {
                capName = capName + 'ters';
              } else if (lowerCap.endsWith('formatter')) {
                capName = capName + 's';
              } else if (lowerCap.endsWith('analyzer')) {
                capName = capName + 's';
              } else if (lowerCap.endsWith('validator')) {
                capName = capName + 's';
              } else if (lowerCap.endsWith('estimator')) {
                capName = capName + 's';
              } else {
                capName = capName + ' Utilities';
              }
            }
            assignedGroup = capName;
            break;
          }
        }
      }

      if (!assignedGroup) {
        const nameWords = tool.name.replace(/[^a-zA-Z0-9\s]/g, '').split(/\s+/).filter(Boolean);
        if (nameWords.length >= 2) {
          const firstTwo = nameWords.slice(0, 2).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
          if (nameLower.includes('calculator')) {
            assignedGroup = firstTwo + ' Calculators';
          } else if (nameLower.includes('converter')) {
            assignedGroup = firstTwo + ' Converters';
          } else if (nameLower.includes('generator')) {
            assignedGroup = firstTwo + ' Generators';
          } else {
            assignedGroup = firstTwo + ' Utilities';
          }
        }
      }

      if (!assignedGroup) {
        assignedGroup = baseCat.name + ' Utilities';
      }

      if (!grouped[assignedGroup]) {
        grouped[assignedGroup] = [];
      }
      grouped[assignedGroup].push(tool);
    });

    Object.entries(grouped).forEach(([groupName, groupTools]) => {
      const chunks: (typeof categoryTools)[] = [];
      for (let i = 0; i < groupTools.length; i += 50) {
        chunks.push(groupTools.slice(i, i + 50));
      }

      chunks.forEach((chunk, chunkIdx) => {
        const subName = chunks.length > 1 ? `${groupName} - Part ${chunkIdx + 1}` : groupName;
        const subId = chunks.length > 1 ? `${baseCat.id} - ${groupName} - Part ${chunkIdx + 1}` : `${baseCat.id} - ${groupName}`;
        const subSlug = kebabCase(subId);

        const colorGradient = UNIQUE_GRADIENTS[gradientIndex % UNIQUE_GRADIENTS.length];
        gradientIndex++;

        const subCatTagCounts: Record<string, number> = {};
        const bannedSubTags = new Set([
          'tags', 'online', 'master', 'advanced', 'smart', 'browser tool', 'client side', 'universal', 
          'helper', 'utility', 'tool', 'free', 'instant', 'easy', 'quick', 'fast', 'best', 'pro', 
          'simple', 'convert', 'converter', 'app', 'online tool', 'generator', 'generator tool', 'tools', 'client-side',
          baseCat.slug, baseCat.slug.replace('-tools', ''), baseCat.name.toLowerCase(), ...baseCat.name.toLowerCase().split(/\s+/)
        ]);

        chunk.forEach(t => {
          t.tags?.forEach(tag => {
            const clean = tag.toLowerCase().trim();
            if (clean && !bannedSubTags.has(clean) && clean.length > 2) {
              subCatTagCounts[clean] = (subCatTagCounts[clean] || 0) + 1;
            }
          });
        });

        const sortedTags = Object.entries(subCatTagCounts)
          .filter(([_, count]) => count >= 2)
          .sort((a, b) => b[1] - a[1])
          .map(([tag]) => tag.charAt(0).toUpperCase() + tag.slice(1))
          .slice(0, 5);

        finalCategories.push({
          id: subId,
          slug: subSlug,
          name: subName,
          iconName: baseCat.iconName,
          description: baseCat.description,
          colorGradient,
          bgLight: baseCat.bgLight,
          count: chunk.length,
          subCategories: sortedTags.length > 0 ? sortedTags : (baseCat.subCategories || []),
          parentId: baseCat.id,
          parentSlug: baseCat.slug,
          toolSlugs: chunk.map(t => t.slug)
        });
      });
    });
  });

  return finalCategories;
})();

export function getToolsForCategory(categorySlug: string): any[] {
  const cat = CATEGORIES.find(c => c.slug === categorySlug);
  if (!cat) {
    const subs = CATEGORIES.filter(c => c.parentSlug === categorySlug);
    if (subs.length > 0) {
      const allSlugs = subs.flatMap(c => c.toolSlugs);
      const baseTools = SEARCH_INDEX.filter(t => allSlugs.includes(t.slug));
      return baseTools.map(t => {
        const subCat = subs.find(s => s.toolSlugs.includes(t.slug));
        return {
          ...t,
          category: subCat ? subCat.id : t.category
        };
      });
    }
    return [];
  }

  const baseTools = SEARCH_INDEX.filter(t => cat.toolSlugs.includes(t.slug));

  return baseTools.map(t => ({
    ...t,
    category: cat.id
  }));
}
