import fs from 'fs';
import { fileURLToPath } from 'url';
import { WORKING_TOOLS } from '../src/lib/tools-data/index';

const searchItems = WORKING_TOOLS.map(t => ({
  id: t.id,
  slug: t.slug,
  name: t.name,
  shortDesc: t.shortDesc || t.description,
  category: t.category,
  iconName: t.iconName || 'Tool',
  tags: t.tags || [t.slug],
  usageCount: t.usageCount || 10000
})).sort((a, b) => (b.usageCount || 0) - (a.usageCount || 0));

const fileContent = `// Automatically generated by sync - DO NOT EDIT MANUALLY
export interface SearchItem {
  id: string;
  slug: string;
  name: string;
  shortDesc: string;
  category: string;
  iconName: string;
  tags: string[];
  usageCount: number;
}

export const SEARCH_INDEX: SearchItem[] = ${JSON.stringify(searchItems, null, 2)};
`;

const outputPath = fileURLToPath(new URL('../src/lib/search-index.ts', import.meta.url));
fs.writeFileSync(outputPath, fileContent, 'utf8');
console.log('SEARCH_INDEX successfully updated with all ' + searchItems.length + ' tools!');
