// Automatically generated by build-categories.ts - DO NOT EDIT MANUALLY
import { CategoryInfo } from './types';
import { SEARCH_INDEX } from './search-index';

export const STATIC_CATEGORIES: (CategoryInfo & { count: number; subCategories?: string[]; department?: string; parentId?: string; parentSlug?: string })[] = [
  {
    "id": "Accounting & Payroll",
    "slug": "accounting-payroll",
    "name": "Accounting & Payroll",
    "iconName": "Tool",
    "description": "Collection of 24 dedicated client-side browser tools for accounting & payroll.",
    "colorGradient": "from-indigo-500 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 24,
    "subCategories": [
      "Browser tool",
      "Client side",
      "Accounting",
      "Hr & payroll",
      "Universal"
    ],
    "department": "Business & Finance",
    "parentId": "Accounting",
    "parentSlug": "accounting"
  },
  {
    "id": "Agriculture, Energy & Environment",
    "slug": "agriculture-energy-environment",
    "name": "Agriculture, Energy & Environment",
    "iconName": "Tool",
    "description": "Collection of 20 dedicated client-side browser tools for agriculture, energy & environment.",
    "colorGradient": "from-emerald-500 to-teal-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 20,
    "subCategories": [
      "Browser tool",
      "Client side",
      "Agriculture",
      "Electrical & solar",
      "Environment & energy"
    ],
    "department": "Industry & Lifestyle",
    "parentId": "Agriculture",
    "parentSlug": "agriculture"
  },
  {
    "id": "Algebra, Geometry & Statistics",
    "slug": "algebra-geometry-statistics",
    "name": "Algebra, Geometry & Statistics",
    "iconName": "Hash",
    "description": "Collection of 44 dedicated client-side browser tools for algebra, geometry & statistics.",
    "colorGradient": "from-cyan-500 to-sky-600",
    "bgLight": "bg-cyan-50 text-cyan-700",
    "count": 44,
    "subCategories": [
      "Math tools",
      "Browser tool",
      "Client side",
      "Universal",
      "Online"
    ],
    "department": "Math & Science",
    "parentId": "Math Tools",
    "parentSlug": "math-tools"
  },
  {
    "id": "Architecture, Construction & Real Estate",
    "slug": "architecture-construction-real-estate",
    "name": "Architecture, Construction & Real Estate",
    "iconName": "Tool",
    "description": "Collection of 30 dedicated client-side browser tools for architecture, construction & real estate.",
    "colorGradient": "from-pink-500 to-rose-600",
    "bgLight": "bg-pink-50 text-pink-700",
    "count": 30,
    "subCategories": [
      "Browser tool",
      "Client side",
      "Real estate",
      "Engineering",
      "Construction"
    ],
    "department": "Industry & Lifestyle",
    "parentId": "Construction",
    "parentSlug": "construction"
  },
  {
    "id": "Audio, Media & Content Production",
    "slug": "audio-media-content-production",
    "name": "Audio, Media & Content Production",
    "iconName": "Headphones",
    "description": "Collection of 44 dedicated client-side browser tools for audio, media & content production.",
    "colorGradient": "from-pink-500 to-rose-600",
    "bgLight": "bg-pink-50 text-pink-700",
    "count": 44,
    "subCategories": [
      "Browser tool",
      "Client side",
      "Audio tools",
      "Universal",
      "Online"
    ],
    "department": "Media & Content",
    "parentId": "Audio Tools",
    "parentSlug": "audio-tools"
  },
  {
    "id": "Automotive",
    "slug": "automotive",
    "name": "Automotive",
    "iconName": "Tool",
    "description": "Collection of 22 dedicated client-side browser tools for automotive.",
    "colorGradient": "from-amber-500 to-orange-600",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 22,
    "subCategories": [
      "Automotive",
      "Browser tool",
      "Client side",
      "Universal",
      "Online"
    ],
    "department": "Industry & Lifestyle",
    "parentId": "Automotive",
    "parentSlug": "automotive"
  },
  {
    "id": "Business Operations & Management",
    "slug": "business-operations-management",
    "name": "Business Operations & Management",
    "iconName": "Building",
    "description": "Collection of 35 dedicated client-side browser tools for business operations & management.",
    "colorGradient": "from-amber-500 to-orange-600",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 35,
    "subCategories": [
      "Browser tool",
      "Client side",
      "E-commerce",
      "Inventory & logistics",
      "Universal"
    ],
    "department": "Business & Finance",
    "parentId": "E-commerce",
    "parentSlug": "e-commerce"
  },
  {
    "id": "Business Tools",
    "slug": "business-tools",
    "name": "Business Tools",
    "iconName": "Building",
    "description": "Collection of 39 dedicated client-side browser tools for business tools.",
    "colorGradient": "from-cyan-500 to-sky-600",
    "bgLight": "bg-cyan-50 text-cyan-700",
    "count": 39,
    "subCategories": [
      "Business tools",
      "Browser tool",
      "Client side",
      "Online",
      "Master"
    ],
    "department": "Business & Finance",
    "parentId": "Business Tools",
    "parentSlug": "business-tools"
  },
  {
    "id": "Code Syntax, Formatters & Minifiers",
    "slug": "code-syntax-formatters-minifiers",
    "name": "Code Syntax, Formatters & Minifiers",
    "iconName": "AlignLeft",
    "description": "Collection of 63 dedicated client-side browser tools for code syntax, formatters & minifiers.",
    "colorGradient": "from-emerald-500 to-teal-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 63,
    "subCategories": [
      "Developer tools",
      "Browser tool",
      "Client side",
      "Browser",
      "Api"
    ],
    "department": "Developer & Web",
    "parentId": "Developer Tools",
    "parentSlug": "developer-tools"
  },
  {
    "id": "Color Palettes, Gradients & Themes",
    "slug": "color-palettes-gradients-themes",
    "name": "Color Palettes, Gradients & Themes",
    "iconName": "Palette",
    "description": "Collection of 47 dedicated client-side browser tools for color palettes, gradients & themes.",
    "colorGradient": "from-emerald-500 to-teal-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 47,
    "subCategories": [
      "Color tools",
      "Browser tool",
      "Client side",
      "Design",
      "Generator"
    ],
    "department": "Media & Content",
    "parentId": "Color Tools",
    "parentSlug": "color-tools"
  },
  {
    "id": "Color Pickers & Format Converters",
    "slug": "color-pickers-format-converters",
    "name": "Color Pickers & Format Converters",
    "iconName": "Palette",
    "description": "Collection of 39 dedicated client-side browser tools for color pickers & format converters.",
    "colorGradient": "from-indigo-500 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 39,
    "subCategories": [
      "Color tools",
      "Browser tool",
      "Client side",
      "Color",
      "Design"
    ],
    "department": "Media & Content",
    "parentId": "Color Tools",
    "parentSlug": "color-tools"
  },
  {
    "id": "CSS & Frontend Web Tools",
    "slug": "css-frontend-web-tools",
    "name": "CSS & Frontend Web Tools",
    "iconName": "Palette",
    "description": "Collection of 14 dedicated client-side browser tools for css & frontend web tools.",
    "colorGradient": "from-pink-500 to-rose-600",
    "bgLight": "bg-pink-50 text-pink-700",
    "count": 14,
    "subCategories": [
      "Generator",
      "Css",
      "Layout",
      "Box shadow",
      "Calculator"
    ],
    "department": "Developer & Web",
    "parentId": "Developer Tools",
    "parentSlug": "developer-tools"
  },
  {
    "id": "Data & Digital Converters",
    "slug": "data-digital-converters",
    "name": "Data & Digital Converters",
    "iconName": "RefreshCw",
    "description": "Collection of 15 dedicated client-side browser tools for data & digital converters.",
    "colorGradient": "from-cyan-500 to-sky-600",
    "bgLight": "bg-cyan-50 text-cyan-700",
    "count": 15,
    "subCategories": [
      "Converter tools",
      "Browser tool",
      "Client side",
      "Converter",
      "Bytes"
    ],
    "department": "Math & Science",
    "parentId": "Converter Tools",
    "parentSlug": "converter-tools"
  },
  {
    "id": "Date & Time",
    "slug": "date-time",
    "name": "Date & Time",
    "iconName": "Clock",
    "description": "Collection of 28 dedicated client-side browser tools for date & time.",
    "colorGradient": "from-rose-500 to-red-600",
    "bgLight": "bg-rose-50 text-rose-700",
    "count": 28,
    "subCategories": [
      "Date & time",
      "Browser tool",
      "Client side",
      "Online",
      "Master"
    ],
    "department": "Text & Productivity",
    "parentId": "Date & Time",
    "parentSlug": "date-time"
  },
  {
    "id": "Domain, Link & Analytics SEO",
    "slug": "domain-link-analytics-seo",
    "name": "Domain, Link & Analytics SEO",
    "iconName": "Globe",
    "description": "Collection of 47 dedicated client-side browser tools for domain, link & analytics seo.",
    "colorGradient": "from-cyan-500 to-sky-600",
    "bgLight": "bg-cyan-50 text-cyan-700",
    "count": 47,
    "subCategories": [
      "Seo tools",
      "Browser tool",
      "Client side",
      "Seo",
      "Urls"
    ],
    "department": "Developer & Web",
    "parentId": "SEO Tools",
    "parentSlug": "seo-tools"
  },
  {
    "id": "Education",
    "slug": "education",
    "name": "Education",
    "iconName": "Tool",
    "description": "Collection of 30 dedicated client-side browser tools for education.",
    "colorGradient": "from-purple-500 to-violet-600",
    "bgLight": "bg-purple-50 text-purple-700",
    "count": 30,
    "subCategories": [
      "Education",
      "Browser tool",
      "Client side",
      "Universal",
      "Online"
    ],
    "department": "Industry & Lifestyle",
    "parentId": "Education",
    "parentSlug": "education"
  },
  {
    "id": "Encryption, Keys & Certificates",
    "slug": "encryption-keys-certificates",
    "name": "Encryption, Keys & Certificates",
    "iconName": "Lock",
    "description": "Collection of 39 dedicated client-side browser tools for encryption, keys & certificates.",
    "colorGradient": "from-pink-500 to-rose-600",
    "bgLight": "bg-pink-50 text-pink-700",
    "count": 39,
    "subCategories": [
      "Security tools",
      "Browser tool",
      "Client side",
      "Security",
      "Crypto"
    ],
    "department": "Developer & Web",
    "parentId": "Security Tools",
    "parentSlug": "security-tools"
  },
  {
    "id": "Everyday & Cooking Converters",
    "slug": "everyday-cooking-converters",
    "name": "Everyday & Cooking Converters",
    "iconName": "RefreshCw",
    "description": "Collection of 43 dedicated client-side browser tools for everyday & cooking converters.",
    "colorGradient": "from-purple-500 to-violet-600",
    "bgLight": "bg-purple-50 text-purple-700",
    "count": 43,
    "subCategories": [
      "Converter tools",
      "Browser tool",
      "Client side",
      "Converter",
      "Calculator"
    ],
    "department": "Math & Science",
    "parentId": "Converter Tools",
    "parentSlug": "converter-tools"
  },
  {
    "id": "Everyday & Scientific Calculators",
    "slug": "everyday-scientific-calculators",
    "name": "Everyday & Scientific Calculators",
    "iconName": "Compass",
    "description": "Collection of 52 dedicated client-side browser tools for everyday & scientific calculators.",
    "colorGradient": "from-rose-500 to-red-600",
    "bgLight": "bg-rose-50 text-rose-700",
    "count": 52,
    "subCategories": [
      "Calculator tools",
      "Browser tool",
      "Client side",
      "Math",
      "Browser"
    ],
    "department": "Math & Science",
    "parentId": "Calculator Tools",
    "parentSlug": "calculator-tools"
  },
  {
    "id": "File Tools",
    "slug": "file-tools",
    "name": "File Tools",
    "iconName": "Folder",
    "description": "Collection of 30 dedicated client-side browser tools for file tools.",
    "colorGradient": "from-cyan-500 to-sky-600",
    "bgLight": "bg-cyan-50 text-cyan-700",
    "count": 30,
    "subCategories": [
      "File tools",
      "Browser tool",
      "Client side",
      "Universal",
      "Online"
    ],
    "department": "Text & Productivity",
    "parentId": "File Tools",
    "parentSlug": "file-tools"
  },
  {
    "id": "Graphic Assets & Image Studio",
    "slug": "graphic-assets-image-studio",
    "name": "Graphic Assets & Image Studio",
    "iconName": "Sparkles",
    "description": "Collection of 44 dedicated client-side browser tools for graphic assets & image studio.",
    "colorGradient": "from-amber-500 to-orange-600",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 44,
    "subCategories": [
      "Image tools",
      "Browser tool",
      "Client side",
      "Image",
      "Dynamic"
    ],
    "department": "Media & Content",
    "parentId": "Image Tools",
    "parentSlug": "image-tools"
  },
  {
    "id": "Health & Fitness",
    "slug": "health-fitness",
    "name": "Health & Fitness",
    "iconName": "Heart",
    "description": "Collection of 32 dedicated client-side browser tools for health & fitness.",
    "colorGradient": "from-indigo-500 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 32,
    "subCategories": [
      "Health & fitness",
      "Browser tool",
      "Client side",
      "Browser",
      "Master"
    ],
    "department": "Industry & Lifestyle",
    "parentId": "Health & Fitness",
    "parentSlug": "health-fitness"
  },
  {
    "id": "Hospitality, Events & Lifestyle",
    "slug": "hospitality-events-lifestyle",
    "name": "Hospitality, Events & Lifestyle",
    "iconName": "Tool",
    "description": "Collection of 20 dedicated client-side browser tools for hospitality, events & lifestyle.",
    "colorGradient": "from-purple-500 to-violet-600",
    "bgLight": "bg-purple-50 text-purple-700",
    "count": 20,
    "subCategories": [
      "Browser tool",
      "Client side",
      "Restaurant & cafe",
      "Wedding & event",
      "Beauty & salon"
    ],
    "department": "Industry & Lifestyle",
    "parentId": "Beauty & Salon",
    "parentSlug": "beauty-salon"
  },
  {
    "id": "Image Format Converters",
    "slug": "image-format-converters",
    "name": "Image Format Converters",
    "iconName": "RefreshCw",
    "description": "Collection of 19 dedicated client-side browser tools for image format converters.",
    "colorGradient": "from-pink-500 to-rose-600",
    "bgLight": "bg-pink-50 text-pink-700",
    "count": 19,
    "subCategories": [
      "Image tools",
      "Browser tool",
      "Client side",
      "Image",
      "Png"
    ],
    "department": "Media & Content",
    "parentId": "Image Tools",
    "parentSlug": "image-tools"
  },
  {
    "id": "Image Resizers & Compressors",
    "slug": "image-resizers-compressors",
    "name": "Image Resizers & Compressors",
    "iconName": "Crop",
    "description": "Collection of 17 dedicated client-side browser tools for image resizers & compressors.",
    "colorGradient": "from-emerald-500 to-teal-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 17,
    "subCategories": [
      "Image",
      "Image tools",
      "Browser tool",
      "Client side",
      "Resizer"
    ],
    "department": "Media & Content",
    "parentId": "Image Tools",
    "parentSlug": "image-tools"
  },
  {
    "id": "JSON & Developer Data Utilities",
    "slug": "json-developer-data-utilities",
    "name": "JSON & Developer Data Utilities",
    "iconName": "FileJson",
    "description": "Collection of 36 dedicated client-side browser tools for json & developer data utilities.",
    "colorGradient": "from-indigo-500 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 36,
    "subCategories": [
      "Developer tools",
      "Browser tool",
      "Client side",
      "Json",
      "Generator"
    ],
    "department": "Developer & Web",
    "parentId": "Developer Tools",
    "parentSlug": "developer-tools"
  },
  {
    "id": "Legal, Regulatory & Marketing",
    "slug": "legal-regulatory-marketing",
    "name": "Legal, Regulatory & Marketing",
    "iconName": "Tool",
    "description": "Collection of 19 dedicated client-side browser tools for legal, regulatory & marketing.",
    "colorGradient": "from-rose-500 to-red-600",
    "bgLight": "bg-rose-50 text-rose-700",
    "count": 19,
    "subCategories": [
      "Browser tool",
      "Client side",
      "Legal tools",
      "Marketing & advertising",
      "Government & public services"
    ],
    "department": "Business & Finance",
    "parentId": "Government & Public Services",
    "parentSlug": "government-public-services"
  },
  {
    "id": "Loans, Mortgages & Investments",
    "slug": "loans-mortgages-investments",
    "name": "Loans, Mortgages & Investments",
    "iconName": "Home",
    "description": "Collection of 18 dedicated client-side browser tools for loans, mortgages & investments.",
    "colorGradient": "from-blue-500 to-indigo-600",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 18,
    "subCategories": [
      "Browser tool",
      "Client side",
      "Finance tools",
      "Calculator tools",
      "Calculator"
    ],
    "department": "Math & Science",
    "parentId": "Calculator Tools",
    "parentSlug": "calculator-tools"
  },
  {
    "id": "Measurement & Unit Converters",
    "slug": "measurement-unit-converters",
    "name": "Measurement & Unit Converters",
    "iconName": "RefreshCw",
    "description": "Collection of 16 dedicated client-side browser tools for measurement & unit converters.",
    "colorGradient": "from-amber-500 to-orange-600",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 16,
    "subCategories": [
      "Converter",
      "Converter tools",
      "Browser tool",
      "Client side",
      "Length"
    ],
    "department": "Math & Science",
    "parentId": "Converter Tools",
    "parentSlug": "converter-tools"
  },
  {
    "id": "Meta Tag & On-Page SEO",
    "slug": "meta-tag-on-page-seo",
    "name": "Meta Tag & On-Page SEO",
    "iconName": "Share2",
    "description": "Collection of 38 dedicated client-side browser tools for meta tag & on-page seo.",
    "colorGradient": "from-amber-500 to-orange-600",
    "bgLight": "bg-amber-50 text-amber-700",
    "count": 38,
    "subCategories": [
      "Seo",
      "Seo tools",
      "Browser tool",
      "Client side",
      "Meta tags"
    ],
    "department": "Developer & Web",
    "parentId": "SEO Tools",
    "parentSlug": "seo-tools"
  },
  {
    "id": "Passwords, Hashes & Checksums",
    "slug": "passwords-hashes-checksums",
    "name": "Passwords, Hashes & Checksums",
    "iconName": "Shield",
    "description": "Collection of 33 dedicated client-side browser tools for passwords, hashes & checksums.",
    "colorGradient": "from-emerald-500 to-teal-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 33,
    "subCategories": [
      "Security",
      "Security tools",
      "Browser tool",
      "Client side",
      "Crypto"
    ],
    "department": "Developer & Web",
    "parentId": "Security Tools",
    "parentSlug": "security-tools"
  },
  {
    "id": "PDF Inspection & Extraction",
    "slug": "pdf-inspection-extraction",
    "name": "PDF Inspection & Extraction",
    "iconName": "FileCheck",
    "description": "Collection of 26 dedicated client-side browser tools for pdf inspection & extraction.",
    "colorGradient": "from-blue-500 to-indigo-600",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 26,
    "subCategories": [
      "Pdf",
      "Pdf tools",
      "Browser tool",
      "Client side",
      "Inspector"
    ],
    "department": "Media & Content",
    "parentId": "PDF Tools",
    "parentSlug": "pdf-tools"
  },
  {
    "id": "PDF Page & Layout Management",
    "slug": "pdf-page-layout-management",
    "name": "PDF Page & Layout Management",
    "iconName": "FileCheck",
    "description": "Collection of 34 dedicated client-side browser tools for pdf page & layout management.",
    "colorGradient": "from-green-500 to-lime-600",
    "bgLight": "bg-lime-50 text-lime-700",
    "count": 34,
    "subCategories": [
      "Pdf",
      "Pdf tools",
      "Browser tool",
      "Client side",
      "Layout"
    ],
    "department": "Media & Content",
    "parentId": "PDF Tools",
    "parentSlug": "pdf-tools"
  },
  {
    "id": "PDF Security & Document Utilities",
    "slug": "pdf-security-document-utilities",
    "name": "PDF Security & Document Utilities",
    "iconName": "FileCheck",
    "description": "Collection of 22 dedicated client-side browser tools for pdf security & document utilities.",
    "colorGradient": "from-rose-500 to-red-600",
    "bgLight": "bg-rose-50 text-rose-700",
    "count": 22,
    "subCategories": [
      "Pdf tools",
      "Browser tool",
      "Client side",
      "Pdf",
      "Security"
    ],
    "department": "Media & Content",
    "parentId": "PDF Tools",
    "parentSlug": "pdf-tools"
  },
  {
    "id": "Personal Budgeting & Expense Management",
    "slug": "personal-budgeting-expense-management",
    "name": "Personal Budgeting & Expense Management",
    "iconName": "PiggyBank",
    "description": "Collection of 38 dedicated client-side browser tools for personal budgeting & expense management.",
    "colorGradient": "from-green-500 to-lime-600",
    "bgLight": "bg-lime-50 text-lime-700",
    "count": 38,
    "subCategories": [
      "Finance tools",
      "Browser tool",
      "Client side",
      "Smart",
      "Master"
    ],
    "department": "Business & Finance",
    "parentId": "Finance Tools",
    "parentSlug": "finance-tools"
  },
  {
    "id": "Photo Effects & Visual Filters",
    "slug": "photo-effects-visual-filters",
    "name": "Photo Effects & Visual Filters",
    "iconName": "Wand2",
    "description": "Collection of 25 dedicated client-side browser tools for photo effects & visual filters.",
    "colorGradient": "from-purple-500 to-violet-600",
    "bgLight": "bg-purple-50 text-purple-700",
    "count": 25,
    "subCategories": [
      "Image tools",
      "Browser tool",
      "Client side",
      "Image",
      "Filter"
    ],
    "department": "Media & Content",
    "parentId": "Image Tools",
    "parentSlug": "image-tools"
  },
  {
    "id": "Physics & Engineering Converters",
    "slug": "physics-engineering-converters",
    "name": "Physics & Engineering Converters",
    "iconName": "RefreshCw",
    "description": "Collection of 19 dedicated client-side browser tools for physics & engineering converters.",
    "colorGradient": "from-green-500 to-lime-600",
    "bgLight": "bg-lime-50 text-lime-700",
    "count": 19,
    "subCategories": [
      "Converter",
      "Converter tools",
      "Browser tool",
      "Client side",
      "Energy"
    ],
    "department": "Math & Science",
    "parentId": "Converter Tools",
    "parentSlug": "converter-tools"
  },
  {
    "id": "Productivity",
    "slug": "productivity",
    "name": "Productivity",
    "iconName": "Tool",
    "description": "Collection of 39 dedicated client-side browser tools for productivity.",
    "colorGradient": "from-indigo-500 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 39,
    "subCategories": [
      "Productivity",
      "Browser tool",
      "Client side",
      "Universal",
      "Master"
    ],
    "department": "Text & Productivity",
    "parentId": "Productivity",
    "parentSlug": "productivity"
  },
  {
    "id": "Random Value, Game & Data Generators",
    "slug": "random-value-game-data-generators",
    "name": "Random Value, Game & Data Generators",
    "iconName": "Zap",
    "description": "Collection of 43 dedicated client-side browser tools for random value, game & data generators.",
    "colorGradient": "from-blue-500 to-indigo-600",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 43,
    "subCategories": [
      "Generators",
      "Browser tool",
      "Client side",
      "Master",
      "Advanced"
    ],
    "department": "Text & Productivity",
    "parentId": "Generators",
    "parentSlug": "generators"
  },
  {
    "id": "Sales, Tax & Financial Calculators",
    "slug": "sales-tax-financial-calculators",
    "name": "Sales, Tax & Financial Calculators",
    "iconName": "Receipt",
    "description": "Collection of 41 dedicated client-side browser tools for sales, tax & financial calculators.",
    "colorGradient": "from-green-500 to-lime-600",
    "bgLight": "bg-lime-50 text-lime-700",
    "count": 41,
    "subCategories": [
      "Calculator tools",
      "Browser tool",
      "Client side",
      "Calculator",
      "Private"
    ],
    "department": "Math & Science",
    "parentId": "Calculator Tools",
    "parentSlug": "calculator-tools"
  },
  {
    "id": "Technical SEO Utilities",
    "slug": "technical-seo-utilities",
    "name": "Technical SEO Utilities",
    "iconName": "Search",
    "description": "Collection of 17 dedicated client-side browser tools for technical seo utilities.",
    "colorGradient": "from-purple-500 to-violet-600",
    "bgLight": "bg-purple-50 text-purple-700",
    "count": 17,
    "subCategories": [
      "Seo",
      "Json-ld",
      "Seo tools",
      "Browser tool",
      "Client side"
    ],
    "department": "Developer & Web",
    "parentId": "SEO Tools",
    "parentSlug": "seo-tools"
  },
  {
    "id": "Text & Font Generators",
    "slug": "text-font-generators",
    "name": "Text & Font Generators",
    "iconName": "Zap",
    "description": "Collection of 42 dedicated client-side browser tools for text & font generators.",
    "colorGradient": "from-indigo-500 to-blue-600",
    "bgLight": "bg-indigo-50 text-indigo-700",
    "count": 42,
    "subCategories": [
      "Text tools",
      "Browser tool",
      "Client side",
      "Unicode",
      "Generator"
    ],
    "department": "Text & Productivity",
    "parentId": "Text Tools",
    "parentSlug": "text-tools"
  },
  {
    "id": "Text Counters & Analysis",
    "slug": "text-counters-analysis",
    "name": "Text Counters & Analysis",
    "iconName": "Hash",
    "description": "Collection of 29 dedicated client-side browser tools for text counters & analysis.",
    "colorGradient": "from-green-500 to-lime-600",
    "bgLight": "bg-lime-50 text-lime-700",
    "count": 29,
    "subCategories": [
      "Text tools",
      "Browser tool",
      "Client side",
      "Text",
      "Analysis"
    ],
    "department": "Text & Productivity",
    "parentId": "Text Tools",
    "parentSlug": "text-tools"
  },
  {
    "id": "Text Encoders & Converters",
    "slug": "text-encoders-converters",
    "name": "Text Encoders & Converters",
    "iconName": "Lock",
    "description": "Collection of 16 dedicated client-side browser tools for text encoders & converters.",
    "colorGradient": "from-rose-500 to-red-600",
    "bgLight": "bg-rose-50 text-rose-700",
    "count": 16,
    "subCategories": [
      "Text tools",
      "Browser tool",
      "Client side",
      "Text",
      "Converter"
    ],
    "department": "Text & Productivity",
    "parentId": "Text Tools",
    "parentSlug": "text-tools"
  },
  {
    "id": "Text Formatters & Cleaners",
    "slug": "text-formatters-cleaners",
    "name": "Text Formatters & Cleaners",
    "iconName": "AlignLeft",
    "description": "Collection of 38 dedicated client-side browser tools for text formatters & cleaners.",
    "colorGradient": "from-blue-500 to-indigo-600",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 38,
    "subCategories": [
      "Text",
      "Text tools",
      "Browser tool",
      "Client side",
      "List"
    ],
    "department": "Text & Productivity",
    "parentId": "Text Tools",
    "parentSlug": "text-tools"
  },
  {
    "id": "Travel Tools",
    "slug": "travel-tools",
    "name": "Travel Tools",
    "iconName": "Tool",
    "description": "Collection of 16 dedicated client-side browser tools for travel tools.",
    "colorGradient": "from-emerald-500 to-teal-600",
    "bgLight": "bg-emerald-50 text-emerald-700",
    "count": 16,
    "subCategories": [
      "Travel tools",
      "Browser tool",
      "Client side",
      "Universal trip itinerary planner",
      "Online travel budget calculator"
    ],
    "department": "Industry & Lifestyle",
    "parentId": "Travel Tools",
    "parentSlug": "travel-tools"
  },
  {
    "id": "Unit Converters",
    "slug": "unit-converters",
    "name": "Unit Converters",
    "iconName": "RefreshCw",
    "description": "Collection of 27 dedicated client-side browser tools for unit converters.",
    "colorGradient": "from-pink-500 to-rose-600",
    "bgLight": "bg-pink-50 text-pink-700",
    "count": 27,
    "subCategories": [
      "Unit converters",
      "Browser tool",
      "Client side",
      "Universal length unit converter",
      "Volume capacity converter master"
    ],
    "department": "Math & Science",
    "parentId": "Unit Converters",
    "parentSlug": "unit-converters"
  },
  {
    "id": "Web Diagnostics & Networking",
    "slug": "web-diagnostics-networking",
    "name": "Web Diagnostics & Networking",
    "iconName": "Globe",
    "description": "Collection of 47 dedicated client-side browser tools for web diagnostics & networking.",
    "colorGradient": "from-blue-500 to-indigo-600",
    "bgLight": "bg-blue-50 text-blue-700",
    "count": 47,
    "subCategories": [
      "Web",
      "Browser tool",
      "Client side",
      "Networking",
      "Seo"
    ],
    "department": "Developer & Web",
    "parentId": "Data Management",
    "parentSlug": "data-management"
  }
];

export const CATEGORIES: (CategoryInfo & { count: number; subCategories?: string[]; department?: string; parentId?: string; parentSlug?: string })[] = STATIC_CATEGORIES;

export function getToolsForCategory(categorySlug: string): any[] {
  const cat = CATEGORIES.find(c => c.slug === categorySlug);
  if (!cat) return [];
  return SEARCH_INDEX.filter(t => t.category === cat.id || t.category === cat.name);
}
