import React, { useState } from 'react';
import { ChevronRight, AlertTriangle, HelpCircle, ChevronDown, ChevronUp, Scale, CheckCircle, ShieldAlert, FileCode2 } from 'lucide-react';
import { CATEGORIES } from '../lib/categories';
import { useSeo } from '../lib/useSeo';

interface DisclaimerPageProps {
  navigate: (path: string) => void;
}

const TOTAL_CATEGORIES = CATEGORIES.length;
const TOTAL_TOOLS = CATEGORIES.reduce((acc, cat) => acc + (cat.count || 0), 0);

export const DisclaimerPage: React.FC<DisclaimerPageProps> = ({ navigate }) => {
  useSeo({
    title: 'Disclaimer — Public Media Tool',
    description: `Read the official Legal Disclaimer for Public Media Tool (PMT). Understand our independent status, trademark notices, and as-is conditions across our ${TOTAL_TOOLS.toLocaleString()}+ browser tools.`,
    path: '/disclaimer',
  });

  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const faqs = [
    {
      q: "Is Public Media Tool (PMT) affiliated with Google, YouTube, Meta, Instagram, or ByteDance?",
      a: "No. Public Media Tool (PMT) is an entirely independent software development entity. PMT is in no way officially connected, associated, sponsored, endorsed, or partnered with Google LLC, YouTube, Meta Platforms Inc., Instagram, ByteDance Ltd., TikTok, or any of their parent corporations or subsidiaries."
    },
    {
      q: "Can I use PMT financial, mortgage, or tax calculators for binding financial filings or legal decisions?",
      a: "No. All financial estimators, mortgage amortization schedules, tax discount tools, and accounting calculators on PMT are created solely for general informational and educational guidance. They do not constitute certified financial, tax, investment, or legal advice. Users must consult licensed financial advisors or certified public accountants before making critical monetary decisions."
    },
    {
      q: "Are PMT utilities safe for formatting confidential source code or proprietary text?",
      a: "Yes. Because 100% of our code execution occurs locally within your web browser runtime (client-side), no text snippets, source files, passwords, or data parameters are ever uploaded to remote servers. This client-side architecture makes PMT formatting, hashing, and regex tools safe for private workflows."
    },
    {
      q: "Are there licensing fees or commercial usage restrictions on outputs generated by PMT?",
      a: "All browser-based utilities across our catalog of " + TOTAL_TOOLS.toLocaleString() + "+ tools are 100% free for both personal and commercial usage. However, all tools are offered on an as-is basis, meaning PMT provides no commercial warranties or operational liability coverage."
    },
    {
      q: "What should I do if I discover a mathematical error or formula discrepancy in a tool?",
      a: "We strive for complete precision across all math, conversion, and formatting algorithms. If you observe any output discrepancies or edge-case calculation errors, please submit details to our engineering team via the Contact Page so we can inspect and update the utility."
    }
  ];

  const handleHomeClick = (e: React.MouseEvent) => {
    e.preventDefault();
    navigate('/');
  };

  return (
    <div className="pt-6 sm:pt-12 pb-16 sm:pb-24 md:pb-32 bg-slate-50 min-h-screen">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8 sm:space-y-12">
        
        {/* Breadcrumb */}
        <nav className="flex items-center text-xs font-semibold text-slate-500 space-x-2" id="disclaimer-breadcrumb">
          <a
            href="/"
            onClick={handleHomeClick}
            className="hover:text-indigo-600 transition-colors cursor-pointer"
          >
            Home
          </a>
          <ChevronRight className="w-3.5 h-3.5 text-slate-400" />
          <span className="text-slate-900">Disclaimer</span>
        </nav>

        {/* Heading Section */}
        <div className="space-y-2.5 sm:space-y-4 text-center md:text-left">
          <span className="inline-flex items-center gap-1.5 text-[11px] sm:text-xs font-bold uppercase tracking-widest text-amber-600 px-3 sm:px-3.5 py-1 sm:py-1.5 bg-amber-50 rounded-full border border-amber-100">
            <AlertTriangle className="w-3.5 h-3.5" /> Legal Disclaimer & Terms of Notice
          </span>
          <h1 className="text-2xl sm:text-4xl md:text-5xl font-extrabold font-heading text-slate-900 tracking-tight">
            Disclaimer
          </h1>
          <p className="text-xs sm:text-sm text-slate-500">
            Official Operational & Legal Notice • Public Media Tool (PMT)
          </p>
        </div>

        {/* Content Body */}
        <div className="bg-white rounded-2xl sm:rounded-3xl p-5 sm:p-8 md:p-10 border border-slate-200/80 shadow-xs space-y-6 sm:space-y-8 text-xs sm:text-base text-slate-600 leading-relaxed">
          
          <section className="space-y-2 sm:space-y-4">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <Scale className="w-5 h-5 sm:w-5.5 sm:h-5.5 text-amber-600" /> 1. Operational "As-Is" Provision & Express Warranty Disclaimer
            </h2>
            <p>
              The web applications, algorithms, conversion engines, financial calculators, unit formatters, image converters, and developer utilities provided across <strong>Public Media Tool (PMT)</strong> (covering {TOTAL_TOOLS.toLocaleString()}+ tools across {TOTAL_CATEGORIES} departments) are delivered to visitors strictly on an <strong>"as-is"</strong>, <strong>"as-available"</strong>, and <strong>"with all faults"</strong> basis.
            </p>
            <p>
              Public Media Tool makes no express or implied representations, merchantability warranties, guarantees of suitability for specific technical purposes, or fitness assurances regarding the operational uptime, uninterrupted access, or complete mathematical precision of any formula or script embedded within our utilities.
            </p>
          </section>

          <section className="space-y-2 sm:space-y-4">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <ShieldAlert className="w-5 h-5 sm:w-5.5 sm:h-5.5 text-amber-600" /> 2. Complete Platform Independence & Trademark Notices
            </h2>
            <p>
              <strong>Public Media Tool (PMT)</strong> is a self-funded, independent software project engineered using client-side browser technologies. PMT is completely independent and maintains no corporate affiliation, legal connection, sponsorship, formal authorization, or endorsement from any third-party technology company or brand mentioned on our site.
            </p>
            <p>
              All trademarks, trade names, registered service marks, corporate logos, and brand graphics referenced across our tool descriptions belong exclusively to their respective intellectual property owners. The inclusion of trademarked brand names (such as web standards, file formats, or social media networks) serves purely descriptive, educational, and nominative utility identification purposes under fair use principles.
            </p>
          </section>

          <section className="space-y-2 sm:space-y-4">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 sm:w-5.5 sm:h-5.5 text-amber-600" /> 3. Absolute User Responsibility & Operational Risk
            </h2>
            <p>
              Any operational task, decision, calculations, or media transformations executed through publicmediatool.com are conducted entirely at your own discretion and risk. PMT, its developers, maintainers, and contributors assume zero liability for direct, indirect, incidental, or consequential losses—including financial discrepancies, loss of data, hardware malfunction, or business disruptions—that may arise from reliance on our software utilities.
            </p>
            <p>
              For critical scientific computations, high-stakes financial projections, structural engineering calculations, or legal document preparation, users are strongly advised to verify all generated results using certified secondary reference materials or professional consultation.
            </p>
          </section>

          <section className="space-y-2 sm:space-y-4">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <FileCode2 className="w-5 h-5 sm:w-5.5 sm:h-5.5 text-amber-600" /> 4. Mathematical & Algorithmic Precision Limitations
            </h2>
            <p>
              While PMT algorithms are rigorously written and updated according to standardized technical specifications, computational variance can occur due to web browser floating-point rounding arithmetic, local hardware CPU architectures, device locale regional configurations, or browser-specific JavaScript engines. Users should treat outputs as high-grade estimations and double-check outputs where absolute precision is required.
            </p>
          </section>

          <section className="space-y-2 sm:space-y-4">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold font-heading text-slate-900 flex items-center gap-2">
              <Scale className="w-5 h-5 sm:w-5.5 sm:h-5.5 text-amber-600" /> 5. Third-Party Advertisements & Endorsement Disclaimer
            </h2>
            <p>
              Public Media Tool displays contextual third-party advertisements served by Google AdSense to sustain its open operations. PMT does not actively screen, endorse, recommend, or warrant any specific software, products, investment schemes, or digital services promoted in these advertisements.
            </p>
            <p>
              Clicking on any external ad and interacting with the destination service is done solely at your own discretion and monetary risk. PMT assumes zero liability for transactions, software installations, or data policies executed on external ad-redirect destinations.
            </p>
          </section>

          <section className="space-y-2 sm:space-y-4">
            <h2 className="text-lg sm:text-xl md:text-2xl font-bold font-heading text-slate-900">6. Continuous Modification & Service Updates</h2>
            <p>
              PMT reserves the unconditional right to update, modify, refine, optimize, or deprecate any software tool, layout component, mathematical equation, or site page at any time without prior announcement. Updates are performed continuously to maintain browser compatibility, enhance execution speed, and adhere to current web standards.
            </p>
          </section>

        </div>

        {/* FAQ Section */}
        <div className="space-y-4 sm:space-y-6 pt-3 sm:pt-6" id="disclaimer-faq-section">
          <div className="text-center md:text-left space-y-1 sm:space-y-2">
            <h2 className="text-xl sm:text-2xl md:text-3xl font-extrabold font-heading text-slate-900 flex items-center justify-center md:justify-start gap-2">
              <HelpCircle className="w-5 h-5 sm:w-6 sm:h-6 text-indigo-600" /> Legal & Disclaimer FAQ
            </h2>
            <p className="text-xs sm:text-sm text-slate-500">
              Clear answers regarding tool liability, trademarks, precision guarantees, and commercial usage.
            </p>
          </div>

          <div className="space-y-2.5 sm:space-y-3">
            {faqs.map((faq, i) => (
              <div
                key={i}
                className="bg-white rounded-xl sm:rounded-2xl border border-slate-200/80 transition-all shadow-xs overflow-hidden"
              >
                <button
                  onClick={() => toggleFaq(i)}
                  className="w-full flex items-center justify-between p-3.5 sm:p-5 text-left font-bold text-slate-950 font-heading text-xs sm:text-base cursor-pointer hover:bg-slate-50/50 rounded-xl sm:rounded-2xl transition-all"
                >
                  <span className="pr-3 sm:pr-4">{faq.q}</span>
                  {openFaq === i ? (
                    <ChevronUp className="w-4 h-4 sm:w-5 sm:h-5 text-indigo-600 shrink-0" />
                  ) : (
                    <ChevronDown className="w-4 h-4 sm:w-5 sm:h-5 text-slate-400 shrink-0" />
                  )}
                </button>
                {openFaq === i && (
                  <div className="p-3.5 sm:p-5 pt-0 border-t border-slate-100 text-xs sm:text-sm text-slate-600 leading-relaxed">
                    {faq.a}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
};

